# ===== STAGE 1: Build =====
FROM python:3.12-slim AS builder

RUN pip install --no-cache-dir uv

WORKDIR /app

COPY pyproject.toml .
RUN uv pip install --system --no-cache-dir .
RUN uv pip install --system --no-cache-dir alembic

# Копируем исходники
COPY . .

# ===== STAGE 2: Runtime =====
FROM python:3.12-slim

# Создаём non-root пользователя (best practice для безопасности)
RUN useradd --create-home --shell /bin/bash app && \
    chown -R app:app /home/app
USER app
WORKDIR /home/app

# Копируем установленные зависимости и код
COPY --from=builder /usr/local /usr/local
COPY --from=builder /app /home/app

ENTRYPOINT ["sh", "-c", "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"]