"""fix

Revision ID: 7bfc1a3b7538
Revises: 522d79a96d22
Create Date: 2025-12-21 11:34:44.087596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bfc1a3b7538'
down_revision: Union[str, Sequence[str], None] = '522d79a96d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'BLOCKED', name='user_status_enum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'BLOCKED', name='user_status_enum'),
               nullable=True)
    # ### end Alembic commands ###
